### ISSUE TITLE
Feature: initialize kedro-dvc structure

### ISSUE THREAD

**Issue by shaunc** [FactFiber/kedro-dvc#15]
In order to create projects using kedro-dvc, we need to initialize the repo for kedro-dvc use.

Two entrypoints: 
* use cli hook on `kedro new` -- new repository w/ kedro-dvc
* cli `dvc` subcommand with `new` (`kedro dvc new`) -- create project with kedro-dvc-specific structure
* cli `dvc` subcommand with `install` (`kedro dvc install`) -- add kedro-dvc-specific structure to existing project

- [ ] on 'new', along with rest of kedro project creation, create `conf/dvc/` directory, with:
    - [ ] Readme.md file with project layout
    - [ ] `pipelines/` subdirectory -- for the per-pipeline configuration.
- [ ] on 'install', create or restore kedro-dvc configuration in existing project.

In the future `conf/kedro_dvc` will contain other metadata as well. If called when kedro_dvc configuration already exists, do not erase previous configuration.

NOTES: 
1) `conf` shouldn't be hard coded, as can be customized by environment. Use kedro project settings api to get conf dir.
2) `kedro dvc new` needs to be installed in "global" instance of kedro, as doesn't presuppose existence of project.

Cases ONLY FOR `install`:
- [ ] whether or not kedro_dvc configuration already exists
  - [ ] `conf/kedro_dvc` does not exist
  - [ ] `conf/kedro_dvc` already exists
- [ ] where config root
  - [ ] default (conf/ at working tree root)
  - [ ] alternate: [specified in project settings](https://kedro.readthedocs.io/en/latest/04_kedro_project_setup/02_configuration.html?highlight=CONF_ROOT#configuration-root) use `kedro.framework.project.settings`

Scenarios:
- [ ] programmatic call
- [ ] `kedro new` cli hook
- [ ] `kedro dvc new` global command
- [ ] `kedro dvc install`

### Testing considerations:
To test global `new`, `dvc new` create new virtual environment for test. Such an environment can be added as a fixture.

Tasks:
- [x] [~fixture: venv with global kedro install, and current kedro-dvc installed~](https://github.com/FactFiber/kedro-dvc/issues/23)
- [X] [~scenario `kedro new` with hooks~](https://github.com/FactFiber/kedro-dvc/issues/24)
- [X] [~scenario: `kedro dvc new` works same way as `kedro new`~](https://github.com/FactFiber/kedro-dvc/issues/25)
- [ ] [scenario: `kedro dvc install` -- default conf, no existing conf](https://github.com/FactFiber/kedro-dvc/issues/26)
- [ ] [case: not default conf](https://github.com/FactFiber/kedro-dvc/issues/27)
- [ ] [case: already exists: don't overwrite](https://github.com/FactFiber/kedro-dvc/issues/28)
  - [ ] test1: data/ exists, and has custom conf, but pipelines/ doesn't exist: should add pipelines but not overwrite data/

**Update**: pending question https://github.com/kedro-org/kedro/discussions/837#discussioncomment-2216745 we don't have appropriate cli hook for `kedro new` In fact `kedro dvc new` is also optional -- added to backlog. Essential is `kedro dvc install`.

**Comment by shaunc** [comment]
Note: define "metadata exists already" / "metadata does not exist" using pytest cases -- so three tests consuming these cases.

**Comment by shaunc** [comment]
Get CONF_ROOT from `kedro.framework.project.settings.CONF_ROOT`.

**Comment by shaunc** [comment]
Note: done up to "new" hook. Can add as separate issue.
